name: Auto Update YOLO Playlist

on:
  schedule:
    - cron: "0 */1 * * *"   # প্রতি 1 ঘন্টা
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download Playlist
        run: curl -L "https://raw.githubusercontent.com/UraDhura69/iptv-playlist/main/YOLO.m3u8" -o YOLO.m3u

      - name: Push Update
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@email.com"
          git add YOLO.m3u
          git commit -m "update YOLO"
          git push
